### ISSUE TITLE
Unicode crashbug

### ISSUE THREAD

**Issue by ChillerDragon** [chillavanilla/TeeworldsEconMod#15]
The crashlog:
```
[chat]: *** 'leooelisabeth' has left the game
[game]: leave player='9:leooelisabeth'
[chat]: *** The red flag was captured by 'Mr. Teeseeks' (13.06 seconds)
[teamchat]: 3:1:nameless tee: ннннннннннннеееееееееееееккккккккккккккккккккууууууууууууууууууууццццццццццццццццццццйцййцввваааааааааапппппппппппппппÑ
Traceback (most recent call last):
  File "/home/chiller/git/TeeworldsEconMod/src/main.py", line 48, in MainLoop
    line = sys.stdin.readline()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 276: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chiller/git/TeeworldsEconMod/src/main.py", line 97, in <module>
    main(sys.argv[1:])
  File "/home/chiller/git/TeeworldsEconMod/src/main.py", line 94, in main
    MainLoop()
  File "/home/chiller/git/TeeworldsEconMod/src/main.py", line 55, in MainLoop
    say("[WARNING] UnicodeDecodeError! Please contact an admin.")
NameError: name 'say' is not defined
```

**Comment by ChillerDragon** [comment]
Since I still don't know how to reproduce the unicode problem I can't be 100% sure.
But the crashbug should be fixed by this commit bf3233a39ad9c81aa8f7d1ffc320abdea153926a
