### ISSUE TITLE
Discord bridge utf8 bug

### ISSUE THREAD

**Issue by ChillerDragon** [chillavanilla/TeeworldsEconMod#24]
```

line: 0:-2:el pro: Â¡VB 89YUOL
Traceback (most recent call last):
  File "./bot.py", line 46, in <module>
    main()
  File "./bot.py", line 38, in main
    HandleData(line)
  File "./bot.py", line 24, in HandleData
    requests.post("https://discordapp.com/api/webhooks/" + token, data={"content": line})
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 507, in prepare_body
    body = self._encode_params(data)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 104, in _encode_params
    v.encode('utf-8') if isinstance(v, str) else v))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc2' in position 13: surrogates not allowed
```

**Comment by ChillerDragon** [comment]
```
line: *** 'xxx' entered and joined the red team
line: 1:-2:x@xx: Ð¤Ð Ð Ð¤
Traceback (most recent call last):
  File "./bot.py", line 46, in <module>
    main()
  File "./bot.py", line 38, in main
    HandleData(line)
  File "./bot.py", line 24, in HandleData
    requests.post("https://discordapp.com/api/webhooks/" + token, data={"content": line})
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 507, in prepare_body
    body = self._encode_params(data)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 104, in _encode_params
    v.encode('utf-8') if isinstance(v, str) else v))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd0' in position 13: surrogates not allowed

```

**Comment by ChillerDragon** [comment]
```
line: 5:-2:xxx: espaÃ±ol?
Traceback (most recent call last):
  File "./bot.py", line 46, in <module>
    main()
  File "./bot.py", line 38, in main
    HandleData(line)
  File "./bot.py", line 24, in HandleData
    requests.post("https://discordapp.com/api/webhooks/" + token, data={"content": line})
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 507, in prepare_body
    body = self._encode_params(data)
  File "/home/chiller/.local/lib/python3.5/site-packages/requests/models.py", line 104, in _encode_params
    v.encode('utf-8') if isinstance(v, str) else v))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 17: surrogates not allowed
```
