### ISSUE TITLE
Crash: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by ChillerDragon** [chillavanilla/TeeworldsEconMod#47]
```
^@^@[21:29:59][game]: leave player='3:name'
^@^@Traceback (most recent call last):
  File "./src/main.py", line 126, in <module>
    main(sys.argv[1:])
  File "./src/main.py", line 123, in main
    MainLoop()
  File "./src/main.py", line 88, in MainLoop
    HandleData(line[1:20], line[21:]) # cut off the timestamp
  File "./src/main.py", line 61, in HandleData
    player.HandlePlayerLeave(data[:-1]) # chop of newline
  File "/home/chiller/git/TeeworldsEconMod/src/player.py", line 159, in HandlePlayerLeave
    SaveAndDeletePlayer(player)
  File "/home/chiller/git/TeeworldsEconMod/src/player.py", line 72, in SaveAndDeletePlayer
    SaveStats(player)
  File "/home/chiller/git/TeeworldsEconMod/src/save_stats.py", line 9, in SaveStats
    return SaveStatsSQL(player)
  File "/home/chiller/git/TeeworldsEconMod/src/sql_stats.py", line 192, in SaveStatsSQL
    player.a_haxx0r, player.a_blazeit, player.a_satan, player.a_virgin
sqlite3.OperationalError: database is locked
```

**Comment by ChillerDragon** [comment]
Sadly not fixed yet.
